# Generated by Django 5.0.7 on 2024-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
